/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import entity.Session;
import entity.Siswa;
import java.awt.Dimension;
import java.io.File;
import java.sql.Connection;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import service.SiswaService;
/**
 *
 * @author Daus
 */
public class FormCetakRapot extends javax.swing.JFrame {
    SiswaService siswaService;
    /**
     * Creates new form FormCetakRapot
     */
    String sessionName = Session.getSessionName();
    String sessionNip = Session.getSessionNip();
    String sessionAkses = Session.getSessionAkses();
    
    public FormCetakRapot() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setPreferredSize(new Dimension(896, 418));
        this.setResizable(false);
        siswaService = new SiswaService();
        loadSiswa();
        tahunAjaran();
        
        menuBar.add(Box.createHorizontalGlue());
        menuBar.add(menuUser);
        menuBar.add(status);
        menuUser.setText("Login User : " + sessionName);
        if(sessionAkses.equals("2")){
            status.setText("Status User : Guru");
//            labelStatus.setText("Guru");
        }else if(sessionAkses.equals("1")){
            status.setText("Status User : Wali Kelas");
        }else{
           status.setText("Status User : Admin");
        }
//        cmbNis.addActionListener(new FormCetakRapot.ComboBoxListener());
//        inpNamaSiswaReport.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNis = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbTahunAjaran = new javax.swing.JComboBox();
        btnCetakRapot = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        cmbSemester = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenu();
        status = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Form Cetak Laporan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NIS");

        cmbNis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNisActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tahun Ajaran");

        cmbTahunAjaran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCetakRapot.setText("Cetak");
        btnCetakRapot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakRapotActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "1", "2" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Semester");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 206, Short.MAX_VALUE)
                .addComponent(btnCetakRapot, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNis, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnCetakRapot))
                .addGap(83, 83, 83))
        );

        date.setText("Date");
        menuBar.add(date);

        menuUser.setText("User");
        menuBar.add(menuUser);

        status.setText("Status");
        menuBar.add(status);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        FormMenuUtama formMenuUtama = new FormMenuUtama();
        formMenuUtama.setVisible(true);
        formMenuUtama.setTitle("Menu Utama");
//        formMenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCetakRapotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakRapotActionPerformed

        String nis = getCodeComboBox(cmbNis.getSelectedItem().toString());
        String tahun_ajaran = cmbTahunAjaran.getSelectedItem().toString();
        int semester = Integer.parseInt(cmbSemester.getSelectedItem().toString());
        try {
            if(nis.equals("--Pilih--")){
                JOptionPane.showMessageDialog(null, "Nis belum di pilih !");
                cmbNis.requestFocus();
                return;
            }else if(tahun_ajaran.equals("--Pilih--")){
                JOptionPane.showMessageDialog(null, "Tahun Ajaran belum di pilih !");
                cmbTahunAjaran.requestFocus();
                return;
            }else{
                loadCetakRapot(nis,tahun_ajaran,semester);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormCetakRapot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakRapotActionPerformed

    private void cmbNisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbNisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCetakRapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCetakRapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCetakRapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCetakRapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    FormCetakRapot formRapot;
                    formRapot = new FormCetakRapot();
                    formRapot.setVisible(true);
//                    formRapot.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    formRapot.setTitle("Form Cetak Laporan");
                } catch (Exception ex) {
                    Logger.getLogger(FormCetakRapot.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }
    
//    private class ComboBoxListener implements ActionListener{
//        @Override
//        public void actionPerformed(ActionEvent e) {
//            if(cmbNis.getSelectedItem().equals("--Pilih--")){
//                inpNamaSiswaReport.setText("");
//            }else{
//                Siswa siswa=(Siswa) cmbNis.getSelectedItem();
//                inpNamaSiswaReport.setText(siswa.getNama_siswa());
//            }
//        }
//        
//    }
    
    private void loadSiswa() throws Exception{
        cmbNis.removeAllItems();
        List<Siswa> siswa = siswaService.getAllSiswa();
        cmbNis.addItem("--Pilih--");
        
        for(Siswa result : siswa){
            cmbNis.addItem(result.getNis() + " - " + result.getNama_siswa());
        } 
    }
    
    private void tahunAjaran() throws Exception{
        int year = Calendar.getInstance().get(Calendar.YEAR);
        int years = year + 1;
        cmbTahunAjaran.removeAllItems();
        cmbTahunAjaran.addItem("--Pilih--");
        for(int i = 2010 ; i <= year; i++){
            for(int j = i ; j <= i; j++){
                int newYear = j+1;
                cmbTahunAjaran.addItem(i + "/" + newYear);
            }
        }
    }
    
    private void loadCetakRapot(String nis, String tahun_ajaran,int semester) throws Exception{
        try {
            String namaFile = "src"+File.separator+"report"+File.separator+"rapot.jasper";
            Connection conn = service.KoneksiDb.getConnection();

            Map<String,Object> map =  new HashMap<String, Object>();
            map.put("nis", nis);
            map.put("tahun_ajaran", tahun_ajaran);
            map.put("semester", semester);
            JasperPrint jprint = JasperFillManager.fillReport(namaFile.toString(), map, conn);
            if(jprint.getPages().size() != 0){
                JasperViewer.viewReport(jprint,false);
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan !");
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
    private String getCodeComboBox(String param) {
        String code = "";
        String[] arr = param.split(" ");
	code = arr[0];	
	return code;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakRapot;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox cmbNis;
    private javax.swing.JComboBox cmbSemester;
    private javax.swing.JComboBox cmbTahunAjaran;
    private javax.swing.JMenu date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenu status;
    // End of variables declaration//GEN-END:variables
}
