/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import entity.Guru;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import service.*;
/**
 *
 * @author Daus
 */
public class FormGuru extends javax.swing.JFrame {
    GuruService guruService;
    /**
     * Creates new form FormGuru
     */
    public FormGuru() throws Exception {
        guruService = new GuruService();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setPreferredSize(new Dimension(896, 418));
        this.setResizable(false);
        inpNip.setEditable(false);
        actionButton(true, false, false, true);
        actionField(false, false, false, false,false);
        loadTableGuru();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inpNip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inpNamaGuru = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        inpEmail = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        inpPassword = new javax.swing.JPasswordField();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        Akses = new javax.swing.JLabel();
        cmbAkses = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGuru = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        inpCari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Form Guru");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NIP");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Guru");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("E-Mail");

        lblEmail1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail1.setText("Password");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        Akses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Akses.setText("Akses");

        cmbAkses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "Guru", "Wali Kelas" }));

        tabelGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelGuru);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cari guru");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(10, 10, 10)
                                .addComponent(btnBatal)
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(inpNip, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblEmail1)
                            .addComponent(jLabel3)
                            .addComponent(Akses))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inpNamaGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(inpEmail)
                            .addComponent(inpPassword)
                            .addComponent(cmbAkses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inpCari, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inpNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnCari)
                    .addComponent(btnRefresh)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inpNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(inpEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail1)
                            .addComponent(inpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Akses)
                            .addComponent(cmbAkses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnBatal)
                            .addComponent(btnSimpan)
                            .addComponent(btnKeluar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try{
            loadNipGuru();
            actionButton(false, true, true, false);
            actionField(true, true, true, true,true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
            actionButton(true, false, false, true);
            actionField(false, false, false, false,false);
            clearField();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Guru guru = new Guru();
        boolean result = false;
        int akses = 0;
        try {
            if(cmbAkses.getSelectedItem().toString().equals("Guru")){
                akses = 2;
            }else if(cmbAkses.getSelectedItem().toString().equals("Wali Kelas")){
                akses = 1;
            }
            guru.setNip(inpNip.getText());
            guru.setNama_guru(inpNamaGuru.getText());
            guru.setEmail(inpEmail.getText());
            guru.setPassword(inpPassword.getText());
            guru.setAkses(akses);
            if(guru.getNama_guru().equals("")){
                JOptionPane.showMessageDialog(null, "Nama Guru tidak boleh kosong !");
                inpNamaGuru.requestFocus();
            }else if(guru.getEmail().equals("")){
                JOptionPane.showMessageDialog(null, "Email Guru tidak boleh kosong !");
                inpEmail.requestFocus();
            }else if(guru.getPassword().equals("")){
                JOptionPane.showMessageDialog(null, "Password Guru tidak boleh kosong !");
                inpPassword.requestFocus();
            }else{
                int count = validasiGuru(inpNip.getText());
                if(count > 0){
                    result = guruService.updateGuru(guru);
                }else{
                    result = guruService.insertGuru(guru);
                }
             
                if(result){
                    loadTableGuru();
                    JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
                    actionButton(true, false, false, true);
                    actionField(false, false, false, false,false);
                    clearField();
                }else{
                    JOptionPane.showMessageDialog(null, "Data gagal di simpan");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        FormMenuUtama menuUtama = new FormMenuUtama();
        menuUtama.setVisible(true);
//        menuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
        menuUtama.setTitle("Menu Utama");
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String param = inpCari.getText();
        try {
            loadTableGuruByParameter(param);
        } catch (Exception ex) {
            Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            // TODO add your handling code here:
            loadTableGuru();
            inpCari.setText("");
        } catch (Exception ex) {
            Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tabelGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGuruMouseClicked
        // TODO add your handling code here:
        int i = tabelGuru.getSelectedRow();
        String akses = "";
        TableModel model = tabelGuru.getModel();
        inpNip.setText(model.getValueAt(i, 0).toString());
        inpNamaGuru.setText(model.getValueAt(i, 1).toString());
        inpEmail.setText(model.getValueAt(i, 2).toString());
        
        if(model.getValueAt(i, 3).toString().equals("1")){
            akses = "Wali Kelas";
        }else if(model.getValueAt(i, 3).toString().equals("2")){
            akses = "Guru";
        }else{
            akses = "Guru";
        }
        cmbAkses.setSelectedItem(akses);
        actionButton(false, true, true, false);
        actionField(true, true, true, true,true);
    }//GEN-LAST:event_tabelGuruMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            int flag =   flag = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini ?","Konfirmasi", JOptionPane.YES_NO_OPTION);
            if(flag == 0){
                 boolean delete = guruService.hapusGuru(inpNip.getText());
                 if(delete){
                     JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
                     loadTableGuru();
                     actionButton(true, false, false, true);
                    actionField(false, false, false, false,false);
                    clearField();
                 }else{
                     JOptionPane.showMessageDialog(null, "Data gagal di hapus");
                 }
            }
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormGuru formGuru = null;
                try {
                    formGuru = new FormGuru();
//                    formGuru.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    formGuru.setVisible(true);
                    formGuru.setTitle("Form Guru");
                } catch (Exception ex) {
                    Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }
    
    private void loadNipGuru() throws Exception{
        String nip = guruService.noGuru();
        inpNip.setText(nip);
    }
    
    private void loadTableGuru() throws Exception{
        List<Map<String,Object>> list = new ArrayList<Map<String,Object>>();
        DefaultTableModel model = new DefaultTableModel();
        tabelGuru.setModel(model);
        model.getDataVector().removeAllElements();
        model.addColumn("NIP");
        model.addColumn("Nama Guru");
        model.addColumn("E-Mail");
        model.addColumn("Akses");

        try{
            list = guruService.getAllGuru();
            for(int i = 0 ; i < list.size() ; i++){
                Object[] obj = new Object[5];
                obj[0] = list.get(i).get("nip");
                obj[1] = list.get(i).get("nama_guru");
                obj[2] = list.get(i).get("email");
                obj[3] = list.get(i).get("akses");
                obj[4] = list.get(i).get("password");
                model.addRow(obj);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void loadTableGuruByParameter(String param) throws Exception{
        List<Map<String,Object>> list = new ArrayList<Map<String,Object>>();
        DefaultTableModel model = new DefaultTableModel();
        tabelGuru.setModel(model);
        model.getDataVector().removeAllElements();
        model.addColumn("NIP");
        model.addColumn("Nama Guru");
        model.addColumn("E-Mail");
        model.addColumn("Akses");
        try{
            list = guruService.getGuruByParameter(param);
            for(int i = 0 ; i < list.size() ; i++){
                Object[] obj = new Object[4];
                obj[0] = list.get(i).get("nip");
                obj[1] = list.get(i).get("nama_guru");
                obj[2] = list.get(i).get("email");
                obj[3] = list.get(i).get("akses");
                model.addRow(obj);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public int validasiGuru(String nip) throws Exception {
        int count = 0;
        try{
            count = guruService.validasiGuru(nip);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return count;
    }
    
    private void clearField() {
        inpNip.setText("");
        inpNamaGuru.setText("");
        inpEmail.setText("");
        inpPassword.setText("");
    }
    
    private void actionButton(boolean tambah, boolean batal, boolean simpan, boolean keluar) {
        btnTambah.setEnabled(tambah);
        btnBatal.setEnabled(batal);
        btnSimpan.setEnabled(simpan);
        btnKeluar.setEnabled(keluar);
    }
    
    private void actionField(boolean nip, boolean nama_guru, boolean email, boolean password, boolean akses) {
        inpNip.setEnabled(nip);
        inpNamaGuru.setEnabled(nama_guru);
        inpEmail.setEnabled(email);
        inpPassword.setEnabled(password);
        cmbAkses.setEnabled(akses);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Akses;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cmbAkses;
    private javax.swing.JTextField inpCari;
    private javax.swing.JTextField inpEmail;
    private javax.swing.JTextField inpNamaGuru;
    private javax.swing.JTextField inpNip;
    private javax.swing.JPasswordField inpPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JTable tabelGuru;
    // End of variables declaration//GEN-END:variables

    private FormMenuUtama FormMenuUtama() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
}
