/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import entity.Siswa;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;
import service.SiswaService;
/**
 *
 * @author Daus
 */
public class FormCetakRapot extends javax.swing.JFrame {
    SiswaService siswaService;
    /**
     * Creates new form FormCetakRapot
     */
    public FormCetakRapot() throws Exception {
        initComponents();
        siswaService = new SiswaService();
        loadSiswa();
        tahunAjaran();
        cmbNis.addActionListener(new FormCetakRapot.ComboBoxListener());
        inpNamaSiswaReport.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNis = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        inpNamaSiswaReport = new javax.swing.JTextField();
        cmbTahunAjaran = new javax.swing.JComboBox();
        btnCetakRapot = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Form Cetak Laporan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NIS");

        cmbNis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tahun Ajaran");

        inpNamaSiswaReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNamaSiswaReportActionPerformed(evt);
            }
        });

        cmbTahunAjaran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCetakRapot.setText("Cetak");
        btnCetakRapot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakRapotActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCetakRapot, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNis, 0, 104, Short.MAX_VALUE)
                            .addComponent(cmbTahunAjaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpNamaSiswaReport, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpNamaSiswaReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetakRapot)
                    .addComponent(btnKeluar))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpNamaSiswaReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNamaSiswaReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNamaSiswaReportActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        FormMenuUtama formMenuUtama = new FormMenuUtama();
        formMenuUtama.setVisible(true);
        formMenuUtama.setTitle("Menu Utama");
        formMenuUtama.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCetakRapotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakRapotActionPerformed

        String nis = cmbNis.getSelectedItem().toString();
        String tahun_ajaran = cmbTahunAjaran.getSelectedItem().toString();
        try {
            if(nis.equals("--Pilih--")){
                JOptionPane.showMessageDialog(null, "Nis belum di pilih !");
                cmbNis.requestFocus();
                return;
            }else if(tahun_ajaran.equals("--Pilih--")){
                JOptionPane.showMessageDialog(null, "Tahun Ajaran belum di pilih !");
                cmbTahunAjaran.requestFocus();
                return;
            }else{
                loadCetakRapot(nis,tahun_ajaran);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormCetakRapot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakRapotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCetakRapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCetakRapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCetakRapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCetakRapot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    FormCetakRapot formRapot;
                    formRapot = new FormCetakRapot();
                    formRapot.setVisible(true);
                    formRapot.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    formRapot.setTitle("Form Cetak Laporan");
                } catch (Exception ex) {
                    Logger.getLogger(FormCetakRapot.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }
    
    private class ComboBoxListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            if(cmbNis.getSelectedItem().equals("--Pilih--")){
                inpNamaSiswaReport.setText("");
            }else{
                Siswa siswa=(Siswa) cmbNis.getSelectedItem();
                inpNamaSiswaReport.setText(siswa.getNama_siswa());
            }
        }
        
    }
    
    private void loadSiswa() throws Exception{
        cmbNis.removeAllItems();
        List<Siswa> siswa = siswaService.getAllSiswa();
        cmbNis.addItem("--Pilih--");
        
        for(Siswa result : siswa){
            cmbNis.addItem(result);
        } 
    }
    
    private void tahunAjaran() throws Exception{
        int year = Calendar.getInstance().get(Calendar.YEAR);
        int years = year + 1;
        cmbTahunAjaran.removeAllItems();
        cmbTahunAjaran.addItem("--Pilih--");
        for(int i = 2010 ; i <= year; i++){
            for(int j = i ; j <= i; j++){
                int newYear = j+1;
                cmbTahunAjaran.addItem(i + "/" + newYear);
            }
        }
    }
    
    private void loadCetakRapot(String nis, String tahun_ajaran) throws Exception{
        try {
            String namaFile = "src"+File.separator+"report"+File.separator+"rapot.jasper";
            Connection conn = service.KoneksiDb.getConnection();

            Map<String,Object> map =  new HashMap<String, Object>();
            map.put("nis", nis);
            map.put("tahun_ajaran", tahun_ajaran);
            JasperPrint jprint = JasperFillManager.fillReport(namaFile.toString(), map, conn);
            if(jprint.getPages().size() != 0){
                JasperViewer.viewReport(jprint,false);
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan !");
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakRapot;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox cmbNis;
    private javax.swing.JComboBox cmbTahunAjaran;
    private javax.swing.JTextField inpNamaSiswaReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
